export enum ACTFLLevel {
	NOVICE_LOW = "N.L",
	NOVICE_MID = "N.M",
	NOVICE_HIGH = "N.H",
	INTERMEDIATE_LOW = "I.L",
	INTERMEDIATE_MID = "I.M",
	INTERMEDIATE_HIGH = "I.H",
	ADVANCED_LOW = "A.L",
	ADVANCED_MID = "A.M",
	ADVANCED_HIGH = "A.H",
	SUPERIOR = "S"
}